### PR TITLE
Set customer key on internal row

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by azkumar** [comment]
hi @smunuswami, I am getting the same error and seems this merge request would fix the issue in delete row. Could you please take a look? 
Thanks!

**Comment by davidOlsonSpfcu** [comment]
@Philippus any update on when this fix will be implemented or if there is a workaround?

**Comment by Philippus** [comment]
I am not an admin of this repository so it's out of my hands.
Workaround for me was creating a new class extending `CustomDataExtension` overriding the `delete`-method and applying the fix in there.

**Comment by Philippus** [comment]
Closing as we're no longer using this library and I want to clear up my queue.

**Pull request closed without merging**
